#+Title:Writing log for this hot paper
#+Options: toc:nil author:nil
#+LaTeX_CLASS:article
#+LaTeX_CLASS_OPTIONS:[11pt,letterpaper]
# \documentclass[10pt,letterpaper]{article}
#+LaTeX_HEADER:\usepackage{amsmath}
#+LaTeX_HEADER:\usepackage{amsfonts}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{makeidx}
#+LaTeX_HEADER:\usepackage{graphicx}
#+LaTeX_HEADER:\usepackage{hyperref}
#+LaTeX_HEADER:\usepackage[letterpaper, total={7in, 9in}]{geometry}
#+LaTeX_HEADER:\usepackage{datetime2}
#+LaTeX_HEADER:\usepackage{minted}
#+LaTeX_HEADER:\usepackage{ulem}
#+LaTeX_HEADER:\usepackage{spreadtab}
# #+LaTeX_HEADER:\usepackage{setspace} \singlespacing
#+LaTeX_HEADER:%Print page numbers in the upper right corner rather than the bottom center.
#+LaTeX_HEADER:\pagestyle{myheadings}
#+LaTeX_HEADER:% Code for plotting table 
#+LaTeX_HEADER:\usepackage{pgfplots}
#+LaTeX_HEADER:\usepackage{pgfplotstable}
#+LaTeX_HEADER:\usepackage{booktabs}
#+LaTeX_HEADER:\usepackage{array}
#+LaTeX_HEADER:\usepackage{colortbl}
#+LaTeX_HEADER:\pgfplotstableset{% global config, for example in the preamble
#+LaTeX_HEADER:  every head row/.style={before row=\toprule,after row=\midrule},
#+LaTeX_HEADER:  every last row/.style={after row=\bottomrule},
#+LaTeX_HEADER:  fixed,precision=2,
#+LaTeX_HEADER:}
#+LaTeX_HEADER:% todolist env from https://tex.stackexchange.com/questions/247681/how-to-create-checkbox-todo-list
#+LaTeX_HEADER:% done with checkmark, wontfix with x, next with finger.
#+LaTeX_HEADER:% Use square brackets around the commands: e.g., [\next]
#+LaTeX_HEADER:\usepackage{enumitem,amssymb}
#+LaTeX_HEADER:\newlist{todolist}{itemize}{2}
#+LaTeX_HEADER:\setlist[todolist]{label=$\square$}
#+LaTeX_HEADER:\usepackage{pifont}
#+LaTeX_HEADER:\newcommand{\nmark}{\ding{42}}% next
#+LaTeX_HEADER:\newcommand{\cmark}{\ding{51}}% checkmark
#+LaTeX_HEADER:\newcommand{\xmark}{\ding{55}}% x-mark
#+LaTeX_HEADER:\newcommand{\wmark}{\ding{116}}% wait mark, inverted triangle representing yield sign
#+LaTeX_HEADER:\newcommand{\done}{\rlap{$\square$}{\raisebox{2pt}{\large\hspace{1pt}\cmark}}%
#+LaTeX_HEADER:  \hspace{-2.5pt}}
#+LaTeX_HEADER:\newcommand{\wontfix}{\rlap{$\square$}{\large\hspace{1pt}\xmark}}
#+LaTeX_HEADER:\newcommand{\waiting}{\rlap{\raisebox{0.18ex}{\hspace{0.17ex}\scriptsize \wmark}}$\square$}
#+LaTeX_HEADER:% \newcommand{\next}{\nmark}%
#+LaTeX_HEADER:\bibliographystyle{cell}
#+Latex_HEADER:\makeindex
#+Latex_HEADER:\title{Writing Log for hot paper}
#+Latex_HEADER:\author{Blaine Mooers}

#+LaTeX:\maketitle


#+LaTeX:\tableofcontents





* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:CLASS: unnumbered
:END:
This template contains a table of contents, numbered outline, and an
index that support navigating the document when it has been rendered
into a PDF. The label and ref macros are part of LaTeX's hyperlinking
system. Items in the table of contents and in the index are hyperlinked
to sites in the body of the writing log. When the tex file is being
viewed on Overleaf, the file outline will appear in the left column. You
can navigate to different sections of the document by clicking on the
file outline in this left column.

*Version 0.3* is a massive restructuring into four sections for improved clarity and
simplicity. The comments in the sections below can be commented out with
a good text editor or by inserting a percent sign at the start of each
line. Some of the explanatory text some may have value in the future.
You can always comment out the lines that contain the explanatory text
by inserting a percent sign at the start of each line. In Overleaf, you
would can select the block of text and then enter command-/ to comment
out the block.

* Project initiation
:PROPERTIES:
:CUSTOM_ID: project-initiation
:END:
** Rationale for this article
:PROPERTIES:
:CUSTOM_ID: sub:why
:END:
What is the rationale for writing this paper? To help advance the field?
To help win or renew a grant funding? To establish credibility in a new
field for my lab?

** Audience for the paper
:PROPERTIES:
:CUSTOM_ID: sub:audience
:END:
Describe in a paragraph of prose the target audience of this paper.

** Potential target journals for submission
:PROPERTIES:
:CUSTOM_ID: sub:target-journals
:END:
The journal titles are enumerated in descending order of desirability.
You have a plan B journal identified at the time of submission so that
you can respond swiftly if the plan A journal rejects the paper.

1. 
2. 
3. 
4. 

** Related projects
:PROPERTIES:
:CUSTOM_ID: sub:related-projects
:END:
By listing projects that are closely and even somewhat distantly related
to the project at hand, it is possible to identify some synergies that
might otherwise be overlooked. For example, when working in a new area,
it is often useful to capitalize on the investment made in reading in
the new field by capturing those insights in the form of a review
article or book chapter. If you use Overleaf, you can include a
hyperlink to the project's webpage.

- 
- 
- 
- 

** Draft Introduction
:PROPERTIES:
:CUSTOM_ID: subsec:Introduction
:END:
In this section and in the next two sections, we assemble the key
components of the paper. You may wonder why we did not do this in the
manuscript document. We find it easier to keep this prose close to the
other lists in the sections that follow these subsections. In other
words, we are using the writing log as an incubator for the initial
drafts of these components of the paper.

We craft a two-paragraph introduction following the method of Lindsay
(Lindsay 2020 Scientific Writing Thinking In Words 2nd Ed). We do this
drafting in the writing log until we are satisfied that we have a vision
of the project that is clear enough to proceed. At this point, we
transfer the draft introduction to the main manuscript.

** Potential results
:PROPERTIES:
:CUSTOM_ID: subsec:Results.
:END:
This section contains a list of the potential key results that are vital
to addressing the central hypothesis. Usually, there are 4 to 6 key
results. Yes, we can think about the nature of the results even before
we have performed the experiments.

We are not necessarily thinking about the expected results, but we can
guess about the nature of the results with regard to whether they will
be in the form of a table, a graph or an image. We then do an initial
sorting of the results on the basis of how much weight they bear upon
testing the central hypothesis. This sorting will be the order in which
the results are presented, in contrast to the general tendency to
deliver the results in the order in which we obtain the results. At this
point, we might even draft an initial paragraph for the results section
that outlines the order of the results. This initial paragraph helps to
set the reader's expectations about the results that follow. After this
initial paragraph is assembled and the planned results are listed, we
will transfer this text to the main manuscript.

1. 
2. 
3. 
4. 
5. 
6. 

** Potential discussion points
:PROPERTIES:
:CUSTOM_ID: subsec:futureDiscussion
:END:
After some years of experience in a particular field, one has a sense of
the critical discussion points about how the proposed results will
relate to the results from the work of others. The content of this
discussion is supposed to be about the relationship of our results to
those reported by others. Sometimes, we expand these discussion points
into initial paragraphs. After we think this section is well-developed,
we will transfer it to the main manuscript.

** Prior discussion points
:PROPERTIES:
:CUSTOM_ID: subsec:priorDiscussion
:END:
The discussion section should contain new points of discussion. If you
are writing a series of papers about a topic, it is all too easy to
recycle old discussion points. Before making the transfer mentioned
above, we will check the proposed discussion points against those we
have published to avoid repeating ourselves and remind ourselves to
review our new results against our prior discussion points. You can
check this list against the discussion section of your current
manuscript to ensure that you are raising new points or updating prior
points while appropriately citing yourself. The new results may require
that we update our published discussion points.

1. 
2. 
3. 

** Potential titles
:PROPERTIES:
:CUSTOM_ID: sub:titles
:END:
Titles of 3-7 words long are easier for people to remember. We generally
iterate through enough titles to find one that is catchy. Sometimes,
this requires generating a list of more than 100 titles. This work takes
time and should not be delayed until the day of manuscript submission.

1. 
2. 
3. 

** Potential Keywords
:PROPERTIES:
:CUSTOM_ID: sub:keywords
:CLASS: unnumbered
:END:
Below is a list of potential keywords. Abstracting services use the
title and abstract to extract terms for searching. As a result, select
keywords that are not in these two parts of the paper. Usually, there is
a limit on the number of keywords, so we choose the keywords carefully.
We make a long list of keywords and select the best ones.

1. open science

2. 

3. 

** Potential Abstract
:PROPERTIES:
:CUSTOM_ID: potential-abstract
:CLASS: unnumbered
:END:
After filling in the above subsections, we are in a solid position to
draft the abstract for the paper. This is just a draft and will be
updated as the results emerge. However, going through this exercise is
another way of visualizing the paper's contents and helps to strengthen
that vision. Such clarity is essential to maintain momentum.

** Abbreviations
:PROPERTIES:
:CUSTOM_ID: sub:abbrev
:END:
A common mistake is to delay the assembly of the list of acronyms and
abbreviations. An incomplete list tells the reviewer that the authors
assembled the manuscript in a hurry.

#+begin_quote
Acronyms/Abbreviations/Initialisms should be defined the first time they
appear in each of three sections: the abstract; the main text; the first
figure or table. When defined for the first time, the
acronym/abbreviation/initialism should be added in parentheses after the
written-out form.

#+end_quote

Abbreviations are also listed at the end of the manuscript.

- abbrev :: its expansion

- abbrev :: its expansion

- abbrev :: its expansion

- abbrev :: its expansion

** Potential collaborators: name; institution;e-mail
:PROPERTIES:
:CUSTOM_ID: sub:collaborators
:END:
- 
- 

** Potential competitors: name; institution;e-mail
:PROPERTIES:
:CUSTOM_ID: sub:competitors
:END:
- 
- 

** Potential reviewers: name; institution;e-mail
:PROPERTIES:
:CUSTOM_ID: sub:reviewers
:END:
1. 
2. 

** Draft cover letter
:PROPERTIES:
:CUSTOM_ID: sub:coverletter
:END:
It is never too early to start writing the cover letter for a project.
This letter is another form of summary that is part of the actualization
of the project. If we have enough energy and time left over from
completing the initialization of the writing project, we may proceed to
drafting the cover letter. The advantage of doing so is to capture one's
excitement about the project.

* Daily entries
:PROPERTIES:
:CUSTOM_ID: sec:dailyEntries
:END:
** Daily protocol
:PROPERTIES:
:CUSTOM_ID: sub:entry-protocol
:END:
1. At start of work session, review the timeline
   [[#sub:benchmarks][2.5]], recent daily entries
   [[#sub:daily-log][2.2]], next action item [[#sub:next][2.6]], and
   to-do list [[#sub:to-do][2.7]].

2. Write the goal(s) for the current writing session as a means of
   engaging mentally in the work. This prose could be retained or
   deleted at the end of the work session.

3. At the end of the work session, move finished items to an achievement
   list for the day.

4. Move the unfinished items to the to-do list [[#sub:to-do][2.7]].

5. Identify the next task or action [[#sub:next][2.6]].

6. Update the wordcount.txt file, if you wrote anything
   [[#sub:zk][2.4]].

7. Update the project Sheet in the Writing Progress Workbook
   [[#sub:WPsheet][2.3]].

8. Update your personal knowledge base [[#sub:zk][2.4]].

** Daily Log
:PROPERTIES:
:CUSTOM_ID: sub:daily-log
:END:
*** 2024 January 21
:PROPERTIES:
:CUSTOM_ID: january-21
:END:
Accomplishments:

- 
- 
- 

** Update Writing Progress Notebook
:PROPERTIES:
:CUSTOM_ID: sub:WPsheet
:END:
The writing progress notebook enables the tracking of progress on a
project basis [fn:1]. The Notebook automatically updates sums of words
written and minutes spent across all projects on a given day. It only
takes a few seconds to enter the number of words written and the time
spent for a specific project on that project's Google Sheet. If you have
Voice In plus activated, say the words "open sheet 37" to have the
worksheet for project 37 opened in the web browser. If not, click on
this direct link to the Google Sheet in the compiled PDF of this writing
log [fn:2].

Update the sheet for this project with the total number of minutes spent
on this project and the word count. The word count is accessed in
Overleaf under the menu pull-down. The word count operation has to be
applied to a recently compiled tex document.

** Update Zettelkästen in org-roam
:PROPERTIES:
:CUSTOM_ID: sub:zk
:END:
Update your knowledge base if you found anything worth adding to it. See
section 4 for guidance ([[#subsec:guides:knowledgebase][4.7]]).

** Timeline or Benchmarks
:PROPERTIES:
:CUSTOM_ID: sub:benchmarks
:END:
This section is an outline of benchmarks or deadlines. I include the
deadline dates in square brackets. It is best to try to map out a
timeline so that the project can continue to move forward.

** Next action
:PROPERTIES:
:CUSTOM_ID: sub:next
:END:
List the next task or action to be taken to move the project forward.
The section is supposed to contain one to do item. It is the next task
that needs to be done. The idea to determine in at the end of the
current work session what the next action should be so that you do not
have to spend time selecting the next action item when you return to the
project. This idea came from David Allen, the author of "Getting things
done".

I have to admit that I rarely do this task next. I generally reconsider
all of the pending to do's at the start of my work session, and I often
wind up identifying a new task that was not identified as the "Next
Action" at the end of the last work session. Anyways, you do gain the
Peace of Mind knowing that you have identified the next step, although
you may not take it. If you do not use this section, go ahead and delete
it.

** To be done
:PROPERTIES:
:CUSTOM_ID: sub:to-do
:END:
These are the tasks that are thought to be required to get the project
finished. The prioritizing of the tasks is the hard part. The book "Time
Power" by Charles Hobbs provides helpful helpful guidance.

- 
- 
- 
- 

** Word Count
:PROPERTIES:
:CUSTOM_ID: sub:wordcount
:END:
The word count is stored in wordcount.txt. The word count tends to
approach a plateau in the latter stages of writing.

* Word Count
#+LaTeX:\index{word count}

The word count tends to approach a plateau in the latter stages of writing.


#+Latex:\begin{figure}[H]
#+LaTeX:  \centering
#+LaTeX:  \begin{tikzpicture}
#+LaTeX:    \begin{axis}[
#+LaTeX:      xlabel={Date},
#+LaTeX:      ylabel={Word Count Cumulative},
#+LaTeX:      % legend pos=south east,
#+LaTeX:      % legend entries={},
#+LaTeX:      ]
#+LaTeX:      \addplot table [x=Day,y=Words] {wordcount.txt};
#+LaTeX:    \end{axis}
#+LaTeX:  \end{tikzpicture}
#+LaTeX:\caption{Cummulative word count.}
#+LaTEX:\end{figure}

#+LaTeX:\begin{table}[]
#+LaTeX:  \centering
#+LaTeX:  \pgfplotstabletypeset[
#+LaTeX:  columns/Date/.style={column name=Date},
#+LaTeX:  columns/Day/.style={column name=Day},
#+LaTeX:  columns/Word/.style={column name=Words},
#+LaTeX:  ]{wordcount.txt}
#+LaTeX:  \caption{Date, day and wordcount.}
#+Latex:  \label{tab:my_label}
#+LaTeX:\end{table}







* Future additions and tangents
:PROPERTIES:
:CUSTOM_ID: sec:future
:END:
** Ideas to consider adding to the manuscript
:PROPERTIES:
:CUSTOM_ID: subsec:new-ideas
:END:
- 
- 
- 

*** Introduction
:PROPERTIES:
:CUSTOM_ID: ssubsec:new-ideas:Intro
:END:
- 
- 
- 

*** Results
:PROPERTIES:
:CUSTOM_ID: ssubsec:new-ideas:Results
:END:
- 
- 
- 

*** Discussion
:PROPERTIES:
:CUSTOM_ID: ssubsec:new-ideas:Discussion
:END:
- 
- 
- 

** To be done someday
:PROPERTIES:
:CUSTOM_ID: subsec:someday
:END:
This section stores tasks that are related to the current project and
that may be worth doing someday. Often these tasks are tangential to
addressing the central hypothesis of the paper. This is a place for
capturing those wonderful ideas. Sometimes these ideas blossom into new
projects. This section can capture ideas that might be mentioned in
terms of future work in the discussion section of the manuscript.

- 
- 
- 

** Spin off writing projects
:PROPERTIES:
:CUSTOM_ID: subsec:spinoffs
:END:
-   :: 
-   :: 
-   :: 
-   :: 

* Guidelines, checklists, protocols, helpful hints
:PROPERTIES:
:CUSTOM_ID: sec:guides
:END:
** Tips for using Overleaf
:PROPERTIES:
:CUSTOM_ID: subsec:guides:overleaf
:END:
1. Chrome has the TextArea extension that is needed to run Grammarly in
   Overleaf.

2. Use the shortcuts (new commands defined in the preamble) to save time
   typing.

3. Where shortcuts are not possible, use templates.

4. View Overleaf project with Chrome to be able to run Grammarly via the
   Chrome Grammarly extension.

5. code Snippets can be mapped to voice commands in Voice In Plus.

** Protocol for running Grammarly in Overleaf
:PROPERTIES:
:CUSTOM_ID: subsec:guides:grammarlyInoverleaf
:END:
You must install Grammarly and Textarea extensions for Chrome. With your
project open in Overleaf, open the textarea icon in the upper right of
your browser and check the checkbox. This will convert the PDF viewport
into RichText. Hit the Grammarly icon. Grammarly will check the text in
the RichText viewport. Corrections that you make in the RichText
viewport are applied to your tex file in the left viewport. Note that
the preamble of the document will cause the text to be spread out. You
may have to scroll down a ways to see the document environment.

** Guidelines for debugging the annotated bibliography
:PROPERTIES:
:CUSTOM_ID: subsec:guides:annotDebug
:END:
For a template annotated bibliography, see
https://github.com/MooersLab/annotatedBibliography.

1. Escape with a forward slash the following: &, _, %, and #.

2. Title case the journal titles.

3. Replace unicode characters with LaTeX code: e.g., replace Å with Å.
   Not all LaTeX document classes are compatible with unicode.

4. The primes have to be replaced with '.

5. The vertical red rectangles with a white dot in the middle should be
   replaced with a whitespace.

6. There are two styles in the bibtex world: bibtex and biblatex. We are
   using bibtex. It is simpler. It has fewer fields.

7. Use Google Scholar bibtex over Medline or PubMed biblatex.

8. Often the error is in the bibitem entry above the one indicated in
   the error messages.

9. All interior braces must by followed by a comma, including the last
   one.

10. When stumped, replace the entry with a fresh one from Google
    Scholar.

** Graphical Abstract
:PROPERTIES:
:CUSTOM_ID: subsec:guides:graphicalAbstract
:END:
The following is copied from the Crystal Journal's
[[https://www.mdpi.com/journal/crystals/instructions#preparation][author
guidelines]].

#+begin_quote
A graphical abstract (GA) is an image that appears alongside the text
abstract in the Table of Contents. In addition to summarizing the
content, it should represent the topic of the article in an interesting
way. The GA should be a high-quality illustration or diagram in any of
the following formats: PNG, JPEG, EPS, SVG, PSD or AI. Written text in a
GA should be clear and easy to read, using one of the following fonts:
Times, Arial, Courier, Helvetica, Ubuntu or Calibri. The minimum size
required for the GA is 560 \(\times\) 1100 pixels (height \(\times\)
width). When submitting larger images, please, keep to the same ratio.

#+end_quote

I usually make the mistake of treating the graphical abstract as an
afterthought. Then there is no time to make one during submission of the
manuscript. This can lead to delays or to the journal converting one of
your sub-figures into a graphical abstract. A good example of a
graphical abstract is found
[[https://www.mdpi.com/2073-4352/11/3/273][here]].

** Guidelines for benchmarks
:PROPERTIES:
:CUSTOM_ID: subsec:guides:benchmarks
:END:
** Guidelines for using Writing Progress Notebook
:PROPERTIES:
:CUSTOM_ID: subsec:guides:wpnb
:END:
The writing progress notebook enables the tracking of progress on a
project basis [fn:3]. The Notebook automatically updates sums of words
written and minutes spent across all projects on a given day. It only
takes a few seconds to enter the number of words written and the time
spent for a specific project on that project's Google Sheet. If you have
Voice In plus activated, say the words "open sheet 37" to have the
worksheet for project 37 opened in the web browser. If not, click on
this direct link to the Google Sheet in the compiled PDF of this writing
log [fn:4].

** Guidelines for using a personal knowledge base
:PROPERTIES:
:CUSTOM_ID: subsec:guides:knowledgebase
:END:
If you maintain a knowledge base like a Zettelkästen in org-roam or
Obsidian or Notion, you might consider adding literature notes and
permanent notes at the end of a work session [fn:5] [fn:6]. The name of
the index for this project is =XXXXXXXXX=. Enter =Control-c n f= to find
this project note. This knowledge base can store information that you
may want to use eventually in the paper.

These notes that you may add might be in the form of what are called
*permanent notes* that include new insights or plans for the work. These
thoughts are not directly linked or derived from any particular
reference in the literature. Another kind of note is known as a
*citation note* or *literature note* is derived from a specific
reference. This kind of note will contain the BibTeX cite key.

Although such notes can be stored in an annotated bibliography
(https://github.com/MooersLab/annotatedBibliography), I seem less likely
to utilize this information while working on a manuscript because the
annotated bibliographies are in a different document. Because it is out
of sight, the annotated bibliography is also out of mind.

The advantage of keeping these bits of knowledge inside the writing log
is that you can link the entries made in the daily log section to these
bits of knowledge by using the label and ref macros of LaTeX. You can
also set up label and ref pairs between to-do items and the bits of
knowledge. Some of these notes may refer to a particular reference, so
you can include the cite key with these notes if the reference has been
included in the BibTeX library file sourced at the bottom of this file.

I usually source the BibTeX library file that I am using in the
annotated bibliography for a particular project. Keeping these items
together in one document will improve the odds that you act upon the
collected information, reducing the mental bandwidth you have to commit
to managing this writing log.

Another approach I use sometimes is to include such information on lines
that have been commented out in the manuscript's tex document near where
I want to utilize that information. I must admit that this approach can
become a little unwieldy if the comments span many lines.

If you use the Pomodoro method, you would probably want to commit the
last one or two poms of a work session on a writing project to update
your knowledge base. If you have been lagging on doing such updates, you
may want to commit four to six poms to this kind of work; you might have
to do this over multiple days if you have fallen behind.

* Backmatter
:PROPERTIES:
:CUSTOM_ID: backmatter
:END:


#+Latex:\bibliography{AnnoBibMyBDA}
#+LaTeX:\printindex

[fn:1] [[https://github.com/MooersLab/writing-progress-2024-25]]

[fn:2] [[file:<insert link for specific sheet>][<insert link for specific sheet>]]

[fn:3] [[https://github.com/MooersLab/writing-progress-2024-25]]

[fn:4] [[file:<insert link for specific sheet>][<insert link for specific sheet>]]

[fn:5] [[https://wiki2.org/en/Zettelkasten]]

[fn:6] [[https://wiki2.org/en/Comparison_of_note-taking_software]]
